version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Starting SonarQube analysis..."
      # Testing CI/CD webhook
      - mvn clean verify sonar:sonar -Dsonar.host.url=http://ec2-34-238-232-89.compute-1.amazonaws.com:9000 -Dsonar.login=squ_1f10a940d15b6dd338dddaa5b6a59b78468b5c60
  post_build:
    commands:
      - echo "Build and SonarQube scan completed successfully!"

artifacts:
  files:
    - target/pineapple-1.0-SNAPSHOT.jar

  
